// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *FullStackApplication) DeepCopyInto(out *FullStackApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject implements runtime.Object.
func (in *FullStackApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of the FullStackApplication.
func (in *FullStackApplication) DeepCopy() *FullStackApplication {
	if in == nil {
		return nil
	}
	out := new(FullStackApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of FullStackApplicationList.
func (in *FullStackApplicationList) DeepCopyInto(out *FullStackApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FullStackApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for FullStackApplicationList.
func (in *FullStackApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of the FullStackApplicationList.
func (in *FullStackApplicationList) DeepCopy() *FullStackApplicationList {
	if in == nil {
		return nil
	}
	out := new(FullStackApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for FullStackApplicationSpec.
func (in *FullStackApplicationSpec) DeepCopyInto(out *FullStackApplicationSpec) {
	*out = *in
	if in.WorkflowDAG != nil {
		in, out := &in.WorkflowDAG, &out.WorkflowDAG
		*out = make([]WorkflowNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GitOps != nil {
		in, out := &in.GitOps, &out.GitOps
		*out = new(GitOpsConfig)
		**out = **in
	}
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(ExecutionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy for FullStackApplicationSpec.
func (in *FullStackApplicationSpec) DeepCopy() *FullStackApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(FullStackApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for WorkflowNode.
func (in *WorkflowNode) DeepCopyInto(out *WorkflowNode) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(corev1.NodeAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy for WorkflowNode.
func (in *WorkflowNode) DeepCopy() *WorkflowNode {
	if in == nil {
		return nil
	}
	out := new(WorkflowNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for GitOpsConfig.
func (in *GitOpsConfig) DeepCopyInto(out *GitOpsConfig) {
	*out = *in
}

// DeepCopy for GitOpsConfig.
func (in *GitOpsConfig) DeepCopy() *GitOpsConfig {
	if in == nil {
		return nil
	}
	out := new(GitOpsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ExecutionConfig.
func (in *ExecutionConfig) DeepCopyInto(out *ExecutionConfig) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy for ExecutionConfig.
func (in *ExecutionConfig) DeepCopy() *ExecutionConfig {
	if in == nil {
		return nil
	}
	out := new(ExecutionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for FullStackApplicationStatus.
func (in *FullStackApplicationStatus) DeepCopyInto(out *FullStackApplicationStatus) {
	*out = *in
	if in.LastCompiledAt != nil {
		in, out := &in.LastCompiledAt, &out.LastCompiledAt
		*out = (*in).DeepCopy()
	}
	if in.LintErrors != nil {
		in, out := &in.LintErrors, &out.LintErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy for FullStackApplicationStatus.
func (in *FullStackApplicationStatus) DeepCopy() *FullStackApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(FullStackApplicationStatus)
	in.DeepCopyInto(out)
	return out
}
