// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *FullStackApplication) DeepCopyInto(out *FullStackApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopyObject implements runtime.Object.
func (in *FullStackApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of the FullStackApplication.
func (in *FullStackApplication) DeepCopy() *FullStackApplication {
	if in == nil {
		return nil
	}
	out := new(FullStackApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of FullStackApplicationList.
func (in *FullStackApplicationList) DeepCopyInto(out *FullStackApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FullStackApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for FullStackApplicationList.
func (in *FullStackApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopy returns a deep copy of the FullStackApplicationList.
func (in *FullStackApplicationList) DeepCopy() *FullStackApplicationList {
	if in == nil {
		return nil
	}
	out := new(FullStackApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for FullStackApplicationSpec.
func (in *FullStackApplicationSpec) DeepCopyInto(out *FullStackApplicationSpec) {
	*out = *in
	if in.WorkflowDAG != nil {
		in, out := &in.WorkflowDAG, &out.WorkflowDAG
		*out = make([]WorkflowNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GitOps != nil {
		in, out := &in.GitOps, &out.GitOps
		*out = new(GitOpsConfig)
		**out = **in
	}
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(ExecutionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy for FullStackApplicationSpec.
func (in *FullStackApplicationSpec) DeepCopy() *FullStackApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(FullStackApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for WorkflowNode.
func (in *WorkflowNode) DeepCopyInto(out *WorkflowNode) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(corev1.NodeAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy for WorkflowNode.
func (in *WorkflowNode) DeepCopy() *WorkflowNode {
	if in == nil {
		return nil
	}
	out := new(WorkflowNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for GitOpsConfig.
func (in *GitOpsConfig) DeepCopyInto(out *GitOpsConfig) {
	*out = *in
}

// DeepCopy for GitOpsConfig.
func (in *GitOpsConfig) DeepCopy() *GitOpsConfig {
	if in == nil {
		return nil
	}
	out := new(GitOpsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ExecutionConfig.
func (in *ExecutionConfig) DeepCopyInto(out *ExecutionConfig) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy for ExecutionConfig.
func (in *ExecutionConfig) DeepCopy() *ExecutionConfig {
	if in == nil {
		return nil
	}
	out := new(ExecutionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for FullStackApplicationStatus.
func (in *FullStackApplicationStatus) DeepCopyInto(out *FullStackApplicationStatus) {
	*out = *in
	if in.LastCompiledAt != nil {
		in, out := &in.LastCompiledAt, &out.LastCompiledAt
		*out = (*in).DeepCopy()
	}
	if in.LintErrors != nil {
		in, out := &in.LintErrors, &out.LintErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy for FullStackApplicationStatus.
func (in *FullStackApplicationStatus) DeepCopy() *FullStackApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(FullStackApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// ─────────────────────────────────────────────
//  KttmApp — DeepCopy implementations
//  (normally generated by controller-gen;
//   maintained manually since controller-gen
//   is not available in this environment)
// ─────────────────────────────────────────────

func (in *KttmApp) DeepCopyInto(out *KttmApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *KttmApp) DeepCopy() *KttmApp {
	if in == nil {
		return nil
	}
	out := new(KttmApp)
	in.DeepCopyInto(out)
	return out
}

func (in *KttmApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KttmAppList) DeepCopyInto(out *KttmAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KttmApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *KttmAppList) DeepCopy() *KttmAppList {
	if in == nil {
		return nil
	}
	out := new(KttmAppList)
	in.DeepCopyInto(out)
	return out
}

func (in *KttmAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KttmAppSpec) DeepCopyInto(out *KttmAppSpec) {
	*out = *in
	in.RBAC.DeepCopyInto(&out.RBAC)
	if in.UILayout != nil {
		in, out := &in.UILayout, &out.UILayout
		*out = new(UILayoutSpec)
		(*in).DeepCopyInto(*out)
	}
	in.WorkflowDAG.DeepCopyInto(&out.WorkflowDAG)
	in.Execution.DeepCopyInto(&out.Execution)
	if in.GitOps != nil {
		in, out := &in.GitOps, &out.GitOps
		*out = new(GitOpsSpec)
		**out = **in
	}
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(DebugSpec)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(PolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *KttmAppSpec) DeepCopy() *KttmAppSpec {
	if in == nil {
		return nil
	}
	out := new(KttmAppSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KttmRBACSpec) DeepCopyInto(out *KttmRBACSpec) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]KttmRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *KttmRole) DeepCopyInto(out *KttmRole) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *UILayoutSpec) DeepCopyInto(out *UILayoutSpec) {
	*out = *in
	if in.SchemaConfigMapRef != nil {
		in, out := &in.SchemaConfigMapRef, &out.SchemaConfigMapRef
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomReactBundle != nil {
		in, out := &in.CustomReactBundle, &out.CustomReactBundle
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

func (in *WorkflowDAGSpec) DeepCopyInto(out *WorkflowDAGSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]WorkflowNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ParallelGroups != nil {
		in, out := &in.ParallelGroups, &out.ParallelGroups
		*out = make([]ParallelGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Edges != nil {
		in, out := &in.Edges, &out.Edges
		*out = make([]DAGEdge, len(*in))
		copy(*out, *in)
	}
}

func (in *ParallelGroup) DeepCopyInto(out *ParallelGroup) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ExecutionSpec) DeepCopyInto(out *ExecutionSpec) {
	*out = *in
	if in.Scaling != nil {
		in, out := &in.Scaling, &out.Scaling
		*out = new(ScalingSpec)
		**out = **in
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

func (in *KttmAppStatus) DeepCopyInto(out *KttmAppStatus) {
	*out = *in
	if in.NodeStatuses != nil {
		in, out := &in.NodeStatuses, &out.NodeStatuses
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.LinterResult != nil {
		in, out := &in.LinterResult, &out.LinterResult
		*out = new(LinterResult)
		(*in).DeepCopyInto(*out)
	}
	if in.ScanResult != nil {
		in, out := &in.ScanResult, &out.ScanResult
		*out = new(ScanResult)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *KttmAppStatus) DeepCopy() *KttmAppStatus {
	if in == nil {
		return nil
	}
	out := new(KttmAppStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *LinterResult) DeepCopyInto(out *LinterResult) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *PolicySpec) DeepCopyInto(out *PolicySpec) {
	*out = *in
	if in.PolicyRefs != nil {
		in, out := &in.PolicyRefs, &out.PolicyRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}
