apiVersion: apps/v1
kind: Deployment
metadata:
  name: kttm-operator
  namespace: kttm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: kttm-operator
  template:
    metadata:
      labels:
        control-plane: kttm-operator
    spec:
      serviceAccountName: kttm-admin
      containers:
        - name: manager
          image: kttm-registry.localhost:5001/kttm-operator
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
