package main

import (
	"encoding/json"
	"log"
	"net/http"
	"os"

	"github.com/kubeworkflow/flowengine/api/bff"
	_ "github.com/kubeworkflow/flowengine/docs" // Swagger docs generated by swag
	workflow "github.com/kubeworkflow/flowengine/internal/workflow"
	httpSwagger "github.com/swaggo/http-swagger"
)

// @title KubeWorkFlow API
// @version 1.0
// @description Core Execution Engine API for managing the NextKube graph
// @BasePath /
type server struct{}

// @Summary Health check
// @Description Returns the operational status of the API server
// @Success 200 {object} map[string]string
// @Router /healthz [get]
func (server) health(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, map[string]string{"status": "ok", "service": "nextkube-api"})
}

// @Summary Get Layout Schema
// @Description Returns the dynamic UI layout schema for rendering the intake form
// @Success 200 {object} map[string]any
// @Router /api/schema [get]
func (server) schema(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{
		"title":       "Order intake",
		"description": "Submit an order to the workflow runtime.",
		"fields": []map[string]any{
			{"id": "customer", "label": "Customer", "type": "text", "required": true, "placeholder": "Acme Inc."},
			{"id": "orderId", "label": "Order ID", "type": "text", "required": true, "placeholder": "ORD-1042"},
			{"id": "priority", "label": "Priority", "type": "select", "options": []string{"standard", "expedited", "critical"}},
		},
		"submitLabel": "Start workflow",
	})
}

// @Summary Start Workflow
// @Description Validates and accepts a new workflow definition for execution
// @Accept json
// @Produce json
// @Param definition body map[string]any true "Workflow Definition"
// @Success 202 {object} map[string]string
// @Failure 400 {object} map[string]string
// @Failure 422 {object} map[string]string
// @Router /api/workflows [post]
func (server) workflows(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		w.Header().Set("Allow", http.MethodPost)
		writeJSON(w, http.StatusMethodNotAllowed, map[string]string{"error": "method not allowed"})
		return
	}
	var definition workflow.Definition
	decoder := json.NewDecoder(http.MaxBytesReader(w, r.Body, 1<<20))
	if err := decoder.Decode(&definition); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid workflow JSON"})
		return
	}
	if err := workflow.Validate(definition); err != nil {
		writeJSON(w, http.StatusUnprocessableEntity, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusAccepted, map[string]any{"status": "accepted", "workflow": definition.Name})
}

func writeJSON(w http.ResponseWriter, status int, value any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(value)
}

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	handler := http.NewServeMux()
	api := server{}
	handler.HandleFunc("GET /healthz", api.health)
	handler.HandleFunc("GET /api/schema", api.schema)
	handler.HandleFunc("POST /api/workflows", api.workflows)

	// Initialize Kubernetes Client for BFF
	if err := bff.InitK8sClient(); err != nil {
		log.Printf("Warning: failed to initialize k8s client for BFF: %v", err)
	}

	// BFF Routes for MS2 Visual Canvas File Persistence
	handler.HandleFunc("GET /api/apps", bff.HandleAppList)
	handler.HandleFunc("GET /api/apps/{name}", bff.HandleAppGet)
	handler.HandleFunc("DELETE /api/apps/{name}", bff.HandleAppDelete)
	handler.HandleFunc("PUT /api/apps/{name}/sync", bff.HandleAppSync)

	// BFF Routes for Live Webhook Testing
	handler.HandleFunc("POST /api/test/webhook", bff.HandleCreateWebhookTest)
	handler.HandleFunc("GET /api/test/webhook/{id}", bff.HandleGetWebhookTest)

	// BFF Routes for RBAC & Auth
	handler.HandleFunc("GET /api/auth/permissions", bff.HandleGetPermissions)
	handler.HandleFunc("GET /api/auth/users", bff.HandleListUsers)
	handler.HandleFunc("PUT /api/auth/users/{username}/permissions", bff.HandleUpdateUserPermissions)

	// Swagger UI route
	handler.HandleFunc("/api/docs/", httpSwagger.WrapHandler)

	log.Printf("nextkube API listening on :%s", port)
	log.Fatal(http.ListenAndServe(":"+port, handler))
}
